global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323'] # Adjust for your OS
    metrics_path: '/metrics'